apiVersion: v2
appVersion: 1.2.5
description: ${CHARTNAME} helm package
name: ${CHARTNAME}
version: 5.3.1
keywords:
  - ${CHARTNAME}
home: https://github.com/k8s-at-home/charts/tree/master/charts/${CHARTNAME}
icon: https://${CHARTNAME}.org/icon
sources:
  - https://github.com/${CHARTNAME}/${CHARTNAME}-docker
  - https://github.com/k8s-at-home/charts/tree/master/charts/${CHARTNAME}
maintainers:
  - name: ${CHARTNAME}
    email: ${CHARTNAME}@${CHARTNAME}.com
dependencies:
  - name: common
    repository: https://k8s-at-home.com/charts/
    version: 2.2.1
